### ISSUE TITLE
Issue of debug features

### ISSUE THREAD

**Issue by rayc345** [probe-rs/vscode#104]
When use probe-rs and the vscode extension for MCU debugging, there is no 'memory access', 'disassemble' window in the debug panel, I want to know if this is supported?

**Comment by noppej** [comment]
These are supported. Please see the documentation (two links below) for how they are accessed:

- https://probe.rs/docs/tools/debugger/#use-the-view-binary-data-to-view-and-perform-binary-edits-of-target-memory
- https://probe.rs/docs/tools/debugger/#use-the-disassembly-to-see-the-assembly-code-executed-on-the-target%2C-and-set-instruction-breakpoints-in-this-view
