### ISSUE TITLE
Probe_rs OS Error

### ISSUE THREAD

**Issue by Admsher** [probe-rs/vscode#105]
I have been using arm-none-eabi-gdb to flash my bin file using probe-rs but when i try to connect on port:3333 i get this error message:

GDB:

**Remote debugging using localhost:3333
Ignoring packet error, continuing...
warning: unrecognized item "timeout" in "qSupported" response
Ignoring packet error, continuing...
Ignoring packet error, continuing...
Remote replied unexpectedly to 'vMustReplyEmpty': timeout**

Probe-rs:
**ERROR probe_rs::cmd::dap_server::debug_adapter::protocol:240: Failed to send a response to the client: An established connection was aborted by the software in your host machine. (os error 10053)
probe-rs-debug: Closing debug session from: 127.0.0.1:51962**

The board kit is IMXRT1064 and I am using a DAP server

**Comment by Yatekii** [comment]
GDB cannot use the DAP server :) You need the GDB server for it.

**Comment by Admsher** [comment]
Oh the documentation did not mention that is there any way I can use probe rs for USB debugging??

**Comment by noppej** [comment]
If you specifically want GDB, and not use the probe-rs implementation of DAP for debugging, then perhaps consider the excellent extension at https://github.com/Marus/cortex-debug.
