### ISSUE TITLE
RISCV issues

### ISSUE THREAD

**Issue by MabezDev** [probe-rs/vscode#11]
Finally getting around to trying out debugging with `probe-rs`! It was pretty easy to setup, however I'm running into a few issues.

`probe-rs` is correctly stopping on breakpoints (see bottom left) but the UI is not updating, nor is it filling the variables table.

![image](https://user-images.githubusercontent.com/6977289/136587478-4b006af1-7b41-4900-80e6-785bd1b2baa3.png)

**Comment by Yatekii** [comment]
cc @noppej

**Comment by noppej** [comment]
Hi Scott,

I'm sorry that you're running into problems with this. The UI is actually updating (visible by fact that the `Call Stack` view reports a breakpoint, and that `Variable` view reports "No variable information available". I realize this isn't useful information, but it does help to be precise in helping describe the potential source of the problem. 

The fact that the `Call Stack`  reports it has halted on an `<unknown function>` versus your `atomic_emulation_trap` suggests that the `probe-rs` stack trace is not returning the information we would expect. 

As far as I know, this has never been tested with RISCV based boards, so it will probably require some debugging effort in the `probe-rs` lib. 

I'd be willing to help but will need to acquire a similar dev board. What chip/board are you using?

**Comment by MabezDev** [comment]
Hi Jack,

Thanks for the fast reponse! I'm happy to help in anyway I can, I understand I'm often venturing into uncharted territory with the riscv stuff :D.

> I'd be willing to help but will need to acquire a similar dev board. What chip/board are you using?

I'm using a esp32c3, specifically its [this board](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/hw-reference/esp32c3/user-guide-devkitm-1.html).

**Comment by noppej** [comment]
@Yatekii and @Tiwalun or @Dirbaio ... do any of you have experience with these boards? Am I barking up the wrong tree thinking I can get one of these and find out why the debug isn't working?  Or do you know of foundational stuff missing in the `probe-rs` lib that would prevent support? 

I am just looking for a quick sanity check and whatever pointers your experience might suggest would be useful to proceed.

**Comment by noppej** [comment]
@MabezDev In the meantime, can you please try the following two steps: 

1. In your `launch.json`, add the option `"wire_protocol":"Jtag"`
2. In your `launch.json`, add the option `"console_log_level": "Debug"`, then send me a copy of the output generated in your VSCode Debug Console (I suggest start with a clean console, then connect, and as soon as the device stops at the first breakpoint, end the debug session, then send the output.

**Comment by MabezDev** [comment]
FYI I'm working around another bug, where `"wire_protocol":"Jtag"` is not applied (atleast not to my Jlink). It defaults to SWD regardless of the value of `wire_protocol`. Currently hardcoding it to use Jtag in the code.

Here is the trace you asked for:

[probe-rs-debug-trace-esp32c3.txt](https://github.com/probe-rs/vscode/files/7314621/probe-rs-debug-trace-esp32c3.txt)

**Comment by MabezDev** [comment]
Seems to be having trouble unwinding the stack frames from what I can tell (StackFrameIterator is returning `None`), here's [the elf file](https://github.com/probe-rs/vscode/files/7314666/simple.zip) I'm flashing in case that helps.

**Comment by noppej** [comment]
The elf file is a good resource ... I will dig through it and get back to you.

**Comment by noppej** [comment]
@MabezDev ... can you please send me a copy of your `Cargo.toml` as well as the instructions you use to build the binary?

**Comment by MabezDev** [comment]
Here is the repo: https://github.com/MabezDev/esp32c3-experiments that includes instructions.

**Comment by noppej** [comment]
@MabezDev ... FYI, I have ordered one of these boards, but none were available in Canada, so I'm waiting on international shipment. Will update this once it arrives and I can reproduce the issue.

**Comment by Tiwalun** [comment]
> @Yatekii and @Tiwalun or @Dirbaio ... do any of you have experience with these boards? Am I barking up the wrong tree thinking I can get one of these and find out why the debug isn't working? Or do you know of foundational stuff missing in the `probe-rs` lib that would prevent support?

I'm pretty sure the debugger / unwinding code in probe-rs has some hardcoded assumptions about ARM / Cortex-M right now, especially the stack unwinding code. So I would assume that it doesn't work properly on any RISCV chips, and not that it's related to the specific chip.

**Comment by noppej** [comment]
@Tiwalun ... Thanks for this. While working on the debugger, I got quite familiar with this part of the code, so I'd be happy to help make it more generic. Do you have much experience with RISCV boards? Can you recommend a 'better' (more available and more widely used) one for me to invest in?

**Comment by Tiwalun** [comment]
I've used the following ones, but not sure if they are 'better':

- [HiFive1 Rev B](https://www.sifive.com/boards/hifive1-rev-b)
- [Pinecone BL602](https://pine64.com/product/pinecone-bl602-evaluation-board/)
- [Sipeed Longan Nano](https://www.seeedstudio.com/Sipeed-Longan-Nano-RISC-V-GD32VF103CBT6-Development-Board-p-4205.html)

And availability is probably a general problem right now...

**Comment by MabezDev** [comment]
I've spotted one issue and logged it under the main repo https://github.com/probe-rs/probe-rs/issues/851.

**Comment by noppej** [comment]
Closing as fixed in probe-rs/probe-rs#878
