### ISSUE TITLE
Panic from probe-rs-debugger are eaten 

### ISSUE THREAD

**Issue by jacobrosenthal** [probe-rs/vscode#14]
For instance, it looks like jlink doesnt like speed": 24000"

But was silently not working. When I turned on Debug logging I found the panic

Presumably can watch for the error code of probe-rs-debugger and if its non 0 report and elevate it to error level?

```
[2021-10-28T21:53:54Z DEBUG probe_rs::probe::jlink] Supported speeds: SpeedInfo { base_freq: 10000000, min_div: 10 }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedSpeed(24000)', debugger/src/debugger.rs:297:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by noppej** [comment]
@jacobrosenthal I agree that the VSCode extension should catch these errors and suspect I can make that change relatively easily. This will be especially useful for un-catchable errors like the `stackoveflow` you logged in #15.

On a similar note (and probably more helpful in my opinion), we should work to eliminate all the panics that are catchable, like the `unwrap()` in this issue. 

I am happy to work on both, but won't be able to do so for the next 8 days (I don't currently have access to my personal dev machine). If someone wants to PR a fix to this in the meantime, please DM me and I will be happy to share what I know about how the code base.

**Comment by jacobrosenthal** [comment]
Can confirm this PR. Jlink with wrong speed now gives an Error log, as well as a popover. Thank you!


![Screenshot from 2021-11-15 10-22-09](https://user-images.githubusercontent.com/455796/141826184-ee66af4d-14a4-40fb-89b8-93316b1e7372.png)
![Screenshot from 2021-11-15 10-21-45](https://user-images.githubusercontent.com/455796/141826186-3b02dc1f-3388-4899-b75b-47ea51bfc2b3.png)

**Comment by noppej** [comment]
Great news. Thanks for testing :)
