### ISSUE TITLE
Consistent config key style

### ISSUE THREAD

**Issue by dbrgn** [probe-rs/vscode#17]
Right now the launch config contains a mix of under_score and camelCase:

![image](https://user-images.githubusercontent.com/105168/140658253-0ae79ef7-b214-4d42-8c6b-16492358cee6.png)

This should be consistent. From looking at https://code.visualstudio.com/docs/cpp/launch-json-reference, camelCase seems to be the convention.

The sooner this is corrected, the better (in order to avoid breaking configs later on) 🙂

**Comment by Yatekii** [comment]
I agree that we should change this. I think this can easily be done with serde by telling it to camelCase :)
