### ISSUE TITLE
Add support for github workflows, CI, etc.

### ISSUE THREAD

**Issue by noppej** [probe-rs/vscode#3]
@Yatekii ... I'd like to take you up on your offer to add the `.github` configurations for this workflow.

**Comment by Yatekii** [comment]
Sure, will do :)

I already looked into available actions.
One that would be cool is this one: https://github.com/marketplace/actions/github-action-for-vsce It does automatically release the extension when we tag a commit. I also want this for probe-rs itself.
As for actual CI build I have to do this manually I think :)

**Comment by noppej** [comment]
Nice ... and thank you!   Auto publishing of the extension is a good thing, as I've found the extension dependencies have frequent changes, and VSCode itself has monthly new features.   I'd like to get past the Alpha before we do the first publish to Microsoft Extension Marketplace.

**Comment by noppej** [comment]
@Yatekii  ... thanks for implementing this.
