### ISSUE TITLE
Timeout while attaching to target under reset

### ISSUE THREAD

**Issue by tsadowski** [probe-rs/vscode#59]
Hello,

I had a working setup for debugging a micro:bit in VSCode. But the I decided to update to 0.18.0 and now I just get:

```
 INFO: Triggered DAP Event: Event {
    body: Some(
        Object {
            "message": String("Timeout while attaching to target under reset. This can happen if the target is not responding to the reset sequence. Ensure the chip's reset pin is connected, or try attaching without reset.\n"),
            "severity": String("error"),
        },
    ),
    event: "probe-rs-show-message",
    seq: 4,
    type_: "event",
}

```

I did not alter my launch configuration. Is there anything I need to add?

Cheers,
Torsten

**Comment by noppej** [comment]
There were some changes to the handling of "connectUnderReset".  Can you try it with that setting set to false (default) in the launch.json?

**Comment by tsadowski** [comment]
Thank you very much, That was it!

**Comment by noppej** [comment]
I will update the error message to clarify.
