### ISSUE TITLE
[Feature request] Colorful defmt log

### ISSUE THREAD

**Issue by HaoboGu** [probe-rs/vscode#76]
Hello, I'm using probe-rs-vscode plugin with defmt rtt logger. When I use `probe-rs run` in cli, it prints logs with color:
<img width="1335" alt="image" src="https://github.com/probe-rs/vscode/assets/8640918/ff9ba913-3d9c-4f3e-85a1-9df747441de4">

But when I do debugging using probe-rs-vscode plugin, the log is printed at the `defmt` tab, but without color: 
<img width="1577" alt="image" src="https://github.com/probe-rs/vscode/assets/8640918/6e520663-1d9e-42f5-9501-8d713926db98">

What's I expect:
log with color in defmt tab

**Comment by noppej** [comment]
The extension runs `probe-rs` as a background process, and `defmt-decoder` (or maybe one of its dependencies) disables terminal sequences for color codding.  I am sure this is a solve-able problem, but haven't figured out the solution yet.

In the mean time, you can manually run `probe-rs` [as a server](https://probe.rs/docs/tools/debugger/#connecting-to-a-standalone-probe-rs-dap-server-server), and configure the extension to connect to it. When you do, you will see the color coding you expect.

**Comment by noppej** [comment]
@Tiwalun and/or @Yatekii  ... My experience with `Node` is very limited, but I suspect it is [this spawn option](https://github.com/probe-rs/vscode/blob/642d3de1406e8dc708712255088f2bb7b14df644/src/extension.ts#L509) that is causing the behaviour with `defmt`. 

Does that make sense to you? Any suggestions on how to mitigate?
