### ISSUE TITLE
RTT Terminals won't show up

### ISSUE THREAD

**Issue by hyx0329** [probe-rs/vscode#87]
Extension version: 0.23.0
VSCode version:
- Code OSS: 1.87.1
- VSCodium: 1.87.1

No RTT terminal is opened even when RTT is configured correctly.

It seems there's a mistake in `createRttTerminal`:
https://github.com/probe-rs/vscode/blob/23f7b8a434027754d34864154dcb880da2924e18/src/extension.ts#L200-L205

The `index` will be a string('distinct') rather than a number, while getting element of a list(`rttTerminals`) requires a number. This causes an exception raised.

I'm not familiar with TS but I've tested the following patch:
```diff
diff --git a/src/extension.ts b/src/extension.ts
index ca793ef..0ea8c78 100644
--- a/src/extension.ts
+++ b/src/extension.ts
@@ -197,7 +197,7 @@ class ProbeRSDebugAdapterServerDescriptorFactory implements vscode.DebugAdapterD
                     name: channelName,
                     pty: channelPty,
                 };
-                for (let index in this.rttTerminals) {
+                for (let index = 0; index < this.rttTerminals.length; index++) {
                     var [formerChannelNumber, , ,] = this.rttTerminals[index];
                     if (formerChannelNumber === channelNumber) {
                         this.rttTerminals.splice(+index, 1);
```

Then the RTT terminal comes up.

**Comment by Yatekii** [comment]
Hmm the two should def. not behave differently :/

**Comment by hyx0329** [comment]
Let me see... Oh! It seems `let ... in` will also iterate over the properties of the object. Look at this:
![Screenshot from 2024-03-12 20-24-00](https://github.com/probe-rs/vscode/assets/11469710/9f5152aa-0c8b-470f-b8ba-2b2d27efe33c)
`index` is the string `distinct` XD

**Comment by noppej** [comment]
@hyx0329 This is a good catch, and reading about it a bit more about TS handling lists, it kinda makes sense. I personally think Typescript should be less 'subtle' about this.

Do you want to PR a fix, or would you prefer one of us to just apply your patch?

**Comment by haradric** [comment]
Hi everyone, I have the same issue

- Visual Studio Code: v1.100.2
- probe-rs: v0.28.0 (git commit: crates.io)
- Debugger for probe-rs: 0.24.2 (from marketplace)

Steps to reproduce:
1. generate a project from the template: https://github.com/rp-rs/rp2040-project-template
2. comment `"speed": 4000,` line in the `.vsode/launch.json` (as it causes an error in my case)
3. start debugging

The debug session starts, but I have no rtt output

**Comment by Yatekii** [comment]
This is probably different and tracked in here: https://github.com/probe-rs/probe-rs/issues/3337
